### ISSUE TITLE
How to use with CSS Modules ?

### ISSUE THREAD

**Issue by Sakuyakun** [reactjs/react-transition-group#167]
I have a CSSTransition and Im using with CSS Modules. However, I dont know how to use it.

the jsx file
```javascript
import React, { Component } from "react";
import styles from "./style.scss";
import { Route, Switch, withRouter } from "react-router-dom";
import { TransitionGroup, CSSTransition } from 'react-transition-group'

import Navigation from "./views/navigation";
import ViewIndex from "./views/viewIndex";
import About from "./views/about";
import DatePickerView from './views/datepickerView.jsx';

@withRouter
export default class Routers extends Component {
  constructor(props) {
    super(props);
  }
  render() {
    const {location} = this.props
    const currentKey = location.pathname.split("/")[1] || "/";
    const timeout = { enter: 300, exit: 200 };
    
    return (
      <div className={styles.view}>
        <TransitionGroup>
          <CSSTransition
            key={currentKey}
            timeout={timeout}
            classNames="fade"  //classnames here, what should i do?
            appear
          >
            <Switch location={location}>
              <div className={styles.h100} key={location.path}>
              <Route key={location.key} location={location} component={ViewIndex} path="/" exact />
              <Route key={location.key} location={location} component={DatePickerView} path="/datepickerview" />
              <Route key={location.key} location={location} component={About} path="/about" />
              </div>
            </Switch>
          </CSSTransition>
        </TransitionGroup>
      </div>
    )
  }
}
```

the scss file (using css modules)
```css
.fade-appear,
.fade-enter {
  opacity: 0;
}

.fade-appear-active,
.fade-enter-active {
  transition: opacity .3s linear;
  opacity: 1;
}

.fade-exit {
  transition: opacity .2s linear;
  opacity: 1;
}

.fade-exit-active {
  opacity: 0;
}
```
