### ISSUE TITLE
Transitions break in Chrome 65

### ISSUE THREAD

**Issue by Theartbug** [reactjs/react-transition-group#322]
**Do you want to request a *feature* or report a *bug*?**

This is a bug.

**What is the current behavior?**

The transition with transform and opacity does not work at all in Chrome 65.0.3325.181.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

Component:
```jsx
<CSSTransitionGroup
        className="transition-group"
        transitionName="slide-up"
        transitionAppear={true}
        transitionAppearTimeout={1800 + (index * .05)}
        transitionEnter={false}
        transitionLeave={false}>
         <li className="result" style={{ 'transitionDelay': `${ index * .05 }s` }}>
              //content
         </li>
      </CSSTransitionGroup>
```
CSS:
```css
.slide-up-appear {
  opacity: 0;
  transform: translateY(30px);
  transition: opacity .5s ease, transform .5s ease;
}

.slide-up-appear-active {
  opacity: 1;
  transform: translateY(0px);
}
```

**What is the expected behavior?**

The list items move upward and appear in a staggered form (one after another).

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

Does not work in: Mac OS 10.13.3 Chrome 65.0.3325.181
Works in: Mac OS 10.13.3 Safari 11.0.3 (13604.5.6), Mac OS Chrome 64.0.3282.186
