### ISSUE TITLE
CSS Classes not applying

### ISSUE THREAD

**Issue by garrettmaring** [reactjs/react-transition-group#408]
Inside of my component I have the following code:

```
          <CSSTransition
            in={true}
            timeout={300}
            classNames="test"
            unmountOnExit={true}
          >
            {state => {
              return (
                 <div className="enable-location__footer">
                    <Button size={ButtonSize.Large} text="Enable Location" />
                    <div className="enable-location__footer-help">
                      <span>Need help?</span>
                      <Link>Contact Us</Link>
                    </div>
                    <div className="enable-location__footer-policies">
                      <Link>Privicay Policy</Link>
                      <Link>Terms of Service</Link>
                    </div>
                  </div>
              );
            }}
          </CSSTransition>
```

And the following css copied from the example:

```css
.test-enter {
  opacity: 0.01;
  transform: scale(0.9) translateY(50%);
}
.test-enter-active {
  opacity: 1;
  transform: scale(1) translateY(0%);
  transition: all 300ms ease-out;
}
.test-exit {
  opacity: 1;
  transform: scale(1) translateY(0%);
}
.test-exit-active {
  opacity: 0.01;
  transform: scale(0.9) translateY(50%);
  transition: all 300ms ease-out;

```

I am not seeing the classNames applied and I only see two states (enter, exit) with no actives when logging the `state` variable.

**Version 2.4.0**
