### ISSUE TITLE
Issues state-classNames docs and migrating

### ISSUE THREAD

**Issue by BannukDE** [reactjs/react-transition-group#522]
I just migrated from version 1 and was surprised that all my windows disappeared. :)
Let me give you some suggestions on how to improve your documents and your migration guide:

Note, migration from:
- "react-addons-css-transition-group": "^15.6.2",
- "react-transition-group": "^1.2.1"

1. At least for me the ClassName states start with a point and are not bound, havn't looked deeper in it yet:
Old: ClassName-enter-active
New: ClassName.enter-active
I couldn't read that anywhere in your documents, only a note in a commit "improved .appear" made me look at the right spot.

2. While we use the child className for styling and subcomponents, I find it important to note that the CSSTransition component overwrites the child className. So for a quick migration and test, I just pass this child className to the CSSTransition:
```js
<CSSTransition
 className={`${props.childClassName} TransitionName`}
.
. >
```
3. In the migration guide a short note about the TransitionGroup-Prop "component={null}" would have saved me some time.

Example Old:
```js
<CSSTransitionGroup
  transitionName="CustomTransName"
  transitionEnterTimeout={500}
  transitionLeaveTimeout={300}>
    {this.props.someVar.map((varchild, i) => (
      <div className={this.props.childClassName} key={i}>{varchild}</div>
    ))}
</CSSTransitionGroup>
```
```css
.CustomTransName-enter-active {
  opacity: 1;
  transform: scaleX(1);
  transition: all 500ms ease-in-out;
}
.CustomTransName-enter-done {
  opacity: 1;
  transform: scaleX(1);
}
.CustomTransName-exit-active {
  opacity: 0;
  transform:scaleX(0);
  transition: all 300ms ease-in-out;
}
```
Example Migrated:
```js
<TransitionGroup  component={null}>
  {this.props.someVar.map((varchild, i) => (
    <CSSTransition
      key={i}
      className={`${this.props.childClassName} CustomTransName`}
      timeout={{ enter: 500, exit: 300 }}
    >
      <div>{varchild}</div>
    </CSSTransition>
  ))}
</TransitionGroup>
```
```css
.CustomTransName.enter-active {
  opacity: 1;
  transform: scaleX(1);
  transition: all 500ms ease-in-out;
}
.CustomTransName.enter-done {
  opacity: 1;
  transform: scaleX(1);
}
.CustomTransName.exit-active {
  opacity: 0;
  transform:scaleX(0);
  transition: all 300ms ease-in-out;
}
```
I am going back to make a clean migration, now that everything works.
Thanks for reading and working on that great Modul.
