### ISSUE TITLE
CSSTransition with react-router doesn't work

### ISSUE THREAD

**Issue by cjsjyh** [reactjs/react-transition-group#697]
```js
  const generateRoutes = () =>
    routes.map(route => (
      <Route key={route.path} path={route.path} exact>
        <CSSTransition in={match != null} key={location.key} classNames="page" timeout={500} unmountOnExit>
          <route.component />
        </CSSTransition>
      </Route>
    ))

  return (
    <>
      <div ref={ref}>
        <div className="slide-container">
          <Switch location={location}>{generateRoutes()}</Switch>
        </div>
      </div>
      <Footer />
    </>
  )
```

```css
.page-enter {
  opacity: 0;
  transform: scale(1.1);
}

.page-enter-active {
  opacity: 1;
  transform: scale(1);
  transition: opacity 300ms, transform 300ms;
}

.page-exit {
  opacity: 1;
  transform: scale(1);
}

.page-exit-active {
  opacity: 0;
  transform: scale(0.9);
  transition: opacity 300ms, transform 300ms;
}

```

css is the exact copy of the official document and I tried to replicate JSX part as well. routing works fine but there is no animation. What am I doing wrong?

From the issue below, I found out that `<TransitionGroup>` was causing all the issue so if I can make this work without `TransitionGroup`,  problem will be solved.
