### ISSUE TITLE
*-move class for list transitions

### ISSUE THREAD

**Issue by ericfennis** [reactjs/react-transition-group#786]
I loved the transition component from Vue. And I understand that this library is heavily inspired by it. 
I really enjoying it, but I miss one feature the move transition. Here is an example from the Vue docs: [Vue transition component (Codepen)](https://codepen.io/team/Vue/pen/049211673d3c185fde6b6eceb8baebec)

``` css
.flip-list-move {
  transition: transform 0.8s ease;
}
```

For now I switched to Framer motion for this, but I think framer motion is a bit too big.
